steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.web
      - --build-arg
      - NEXT_PUBLIC_RETEMPO_API_BASE_URL=https://api.retempo.xyz
      - -t
      - asia-southeast1-docker.pkg.dev/signalarc-prod-241205/retempo/retempo-web:phase12-web-001
      - .

images:
  - asia-southeast1-docker.pkg.dev/signalarc-prod-241205/retempo/retempo-web:phase12-web-001
